version: '3.8'

services:
  app:
    build: .
    container_name: react-project
    ports:
      - "5173:5173"  # 로컬 포트와 컨테이너 포트 매핑
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
    working_dir: /app
    tty: true  # 터미널 세션을 유지하여 로그 확인